package com.xy.data.dao;

import java.util.List;

import com.xy.data.service.dsn.model.po.DsnPO;
import com.xy.data.service.dsn.model.po.DsnExample;
import org.apache.ibatis.annotations.Param;

public interface DsnDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dsn
     *
     * @mbg.generated
     */
    long countByExample(DsnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dsn
     *
     * @mbg.generated
     */
    int deleteByExample(DsnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dsn
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dsn
     *
     * @mbg.generated
     */
    int insert(DsnPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dsn
     *
     * @mbg.generated
     */
    int insertSelective(DsnPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dsn
     *
     * @mbg.generated
     */
    List<DsnPO> selectByExample(DsnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dsn
     *
     * @mbg.generated
     */
    DsnPO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dsn
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DsnPO record, @Param("example") DsnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dsn
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DsnPO record, @Param("example") DsnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dsn
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DsnPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dsn
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DsnPO record);
}